# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\94890\Desktop\Mathematical_Statistics\Myfiles\Sd_DoubleNormal.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Sd_DoubleNormal_Form(object):
    def setupUi(self, Sd_DoubleNormal_Form):
        Sd_DoubleNormal_Form.setObjectName("Sd_DoubleNormal_Form")
        Sd_DoubleNormal_Form.resize(991, 600)
        self.widget = Plot(Sd_DoubleNormal_Form)
        self.widget.setGeometry(QtCore.QRect(40, 180, 901, 391))
        self.widget.setObjectName("widget")
        self.layoutWidget = QtWidgets.QWidget(Sd_DoubleNormal_Form)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 120, 901, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.layoutWidget1 = QtWidgets.QWidget(Sd_DoubleNormal_Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 40, 901, 23))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.spinBox_n1 = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBox_n1.setMinimum(2)
        self.spinBox_n1.setMaximum(999999999)
        self.spinBox_n1.setObjectName("spinBox_n1")
        self.horizontalLayout_2.addWidget(self.spinBox_n1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.spinBox_n2 = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBox_n2.setMinimum(2)
        self.spinBox_n2.setMaximum(999999999)
        self.spinBox_n2.setObjectName("spinBox_n2")
        self.horizontalLayout_2.addWidget(self.spinBox_n2)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinBox_m1 = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBox_m1.setMinimum(1)
        self.spinBox_m1.setMaximum(999999999)
        self.spinBox_m1.setObjectName("spinBox_m1")
        self.horizontalLayout_2.addWidget(self.spinBox_m1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.spinBox_m2 = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBox_m2.setMinimum(1)
        self.spinBox_m2.setMaximum(999999999)
        self.spinBox_m2.setObjectName("spinBox_m2")
        self.horizontalLayout_2.addWidget(self.spinBox_m2)
        self.layoutWidget2 = QtWidgets.QWidget(Sd_DoubleNormal_Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(40, 80, 909, 25))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.doubleSpinBox_mu1 = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.doubleSpinBox_mu1.setMinimum(-1e+31)
        self.doubleSpinBox_mu1.setMaximum(1e+28)
        self.doubleSpinBox_mu1.setObjectName("doubleSpinBox_mu1")
        self.horizontalLayout_4.addWidget(self.doubleSpinBox_mu1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.doubleSpinBox_sigma1 = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.doubleSpinBox_sigma1.setMinimum(0.0)
        self.doubleSpinBox_sigma1.setMaximum(1e+28)
        self.doubleSpinBox_sigma1.setObjectName("doubleSpinBox_sigma1")
        self.horizontalLayout_4.addWidget(self.doubleSpinBox_sigma1)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_4)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.doubleSpinBox_mu2 = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.doubleSpinBox_mu2.setMinimum(-1e+31)
        self.doubleSpinBox_mu2.setMaximum(1e+28)
        self.doubleSpinBox_mu2.setObjectName("doubleSpinBox_mu2")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_mu2)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.doubleSpinBox_sigma2 = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.doubleSpinBox_sigma2.setMinimum(0.0)
        self.doubleSpinBox_sigma2.setMaximum(1e+28)
        self.doubleSpinBox_sigma2.setObjectName("doubleSpinBox_sigma2")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_sigma2)

        self.retranslateUi(Sd_DoubleNormal_Form)
        QtCore.QMetaObject.connectSlotsByName(Sd_DoubleNormal_Form)

    def retranslateUi(self, Sd_DoubleNormal_Form):
        _translate = QtCore.QCoreApplication.translate
        Sd_DoubleNormal_Form.setWindowTitle(_translate("Sd_DoubleNormal_Form", "两个正态总体抽样分布"))
        self.pushButton.setText(_translate("Sd_DoubleNormal_Form", "已知方差σ2的两总体的样本均值的分布"))
        self.pushButton_2.setText(_translate("Sd_DoubleNormal_Form", "已知方差σ2的两总体的样本方差比的分布"))
        self.pushButton_3.setText(_translate("Sd_DoubleNormal_Form", "方差σ2相等的两总体的样本均值方差比的分布"))
        self.label.setText(_translate("Sd_DoubleNormal_Form", "样本容量n1"))
        self.label_5.setText(_translate("Sd_DoubleNormal_Form", "样本容量n2"))
        self.label_2.setText(_translate("Sd_DoubleNormal_Form", "抽样次数m1"))
        self.label_6.setText(_translate("Sd_DoubleNormal_Form", "抽样次数m2"))
        self.label_7.setText(_translate("Sd_DoubleNormal_Form", "mu1"))
        self.label_8.setText(_translate("Sd_DoubleNormal_Form", "sigema1"))
        self.label_3.setText(_translate("Sd_DoubleNormal_Form", "mu2"))
        self.label_4.setText(_translate("Sd_DoubleNormal_Form", "sigema2"))

from Plot import Plot

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Sd_DoubleNormal_Form = QtWidgets.QWidget()
    ui = Ui_Sd_DoubleNormal_Form()
    ui.setupUi(Sd_DoubleNormal_Form)
    Sd_DoubleNormal_Form.show()
    sys.exit(app.exec_())

