# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\94890\Desktop\YTfiles\Myfiles\Myfiles\files\FenbuhanshuNihe.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FenbuhanshuNihe_Form(object):
    def setupUi(self, FenbuhanshuNihe_Form):
        FenbuhanshuNihe_Form.setObjectName("FenbuhanshuNihe_Form")
        FenbuhanshuNihe_Form.resize(751, 560)
        self.label = QtWidgets.QLabel(FenbuhanshuNihe_Form)
        self.label.setGeometry(QtCore.QRect(30, 30, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(FenbuhanshuNihe_Form)
        self.lineEdit.setGeometry(QtCore.QRect(190, 30, 411, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.widget = QtWidgets.QWidget(FenbuhanshuNihe_Form)
        self.widget.setGeometry(QtCore.QRect(60, 80, 531, 151))
        self.widget.setObjectName("widget")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(50, 80, 111, 28))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(320, 30, 91, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setGeometry(QtCore.QRect(320, 90, 91, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(260, 30, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(250, 90, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.widget_2 = QtWidgets.QWidget(FenbuhanshuNihe_Form)
        self.widget_2.setGeometry(QtCore.QRect(60, 270, 531, 151))
        self.widget_2.setObjectName("widget_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 70, 111, 28))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(320, 30, 91, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(320, 100, 91, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setGeometry(QtCore.QRect(250, 40, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        self.label_7.setGeometry(QtCore.QRect(240, 100, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")

        self.retranslateUi(FenbuhanshuNihe_Form)
        QtCore.QMetaObject.connectSlotsByName(FenbuhanshuNihe_Form)

    def retranslateUi(self, FenbuhanshuNihe_Form):
        _translate = QtCore.QCoreApplication.translate
        FenbuhanshuNihe_Form.setWindowTitle(_translate("FenbuhanshuNihe_Form", "分布函数拟合"))
        self.label.setText(_translate("FenbuhanshuNihe_Form", "原数据存储路径"))
        self.pushButton.setText(_translate("FenbuhanshuNihe_Form", "检验"))
        self.label_2.setText(_translate("FenbuhanshuNihe_Form", "是否服从正态分布"))
        self.label_4.setText(_translate("FenbuhanshuNihe_Form", "P值"))
        self.label_5.setText(_translate("FenbuhanshuNihe_Form", "结果"))
        self.pushButton_2.setText(_translate("FenbuhanshuNihe_Form", "检验"))
        self.label_3.setText(_translate("FenbuhanshuNihe_Form", "是否服从泊松分布"))
        self.label_6.setText(_translate("FenbuhanshuNihe_Form", "P值"))
        self.label_7.setText(_translate("FenbuhanshuNihe_Form", "结果"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FenbuhanshuNihe_Form = QtWidgets.QWidget()
    ui = Ui_FenbuhanshuNihe_Form()
    ui.setupUi(FenbuhanshuNihe_Form)
    FenbuhanshuNihe_Form.show()
    sys.exit(app.exec_())
