# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\94890\Desktop\YTfiles\Myfiles\Myfiles\files\Linear_regression.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Linear_regression_Form(object):
    def setupUi(self, Linear_regression_Form):
        Linear_regression_Form.setObjectName("Linear_regression_Form")
        Linear_regression_Form.resize(850, 808)
        self.pushButton = QtWidgets.QPushButton(Linear_regression_Form)
        self.pushButton.setGeometry(QtCore.QRect(40, 60, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Linear_regression_Form)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 140, 141, 28))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.widget = Plot(Linear_regression_Form)
        self.widget.setGeometry(QtCore.QRect(50, 260, 741, 351))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.widget.setFont(font)
        self.widget.setObjectName("widget")
        self.layoutWidget = QtWidgets.QWidget(Linear_regression_Form)
        self.layoutWidget.setGeometry(QtCore.QRect(540, 60, 275, 70))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout.addWidget(self.lineEdit_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_2.addWidget(self.lineEdit_4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.layoutWidget1 = QtWidgets.QWidget(Linear_regression_Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 100, 381, 23))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.layoutWidget2 = QtWidgets.QWidget(Linear_regression_Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(50, 180, 751, 66))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_4.addWidget(self.lineEdit_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_5.addWidget(self.lineEdit_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.pushButton_4 = QtWidgets.QPushButton(Linear_regression_Form)
        self.pushButton_4.setGeometry(QtCore.QRect(330, 630, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_6 = QtWidgets.QLabel(Linear_regression_Form)
        self.label_6.setGeometry(QtCore.QRect(30, 640, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(Linear_regression_Form)
        self.lineEdit_7.setGeometry(QtCore.QRect(140, 640, 113, 21))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_7 = QtWidgets.QLabel(Linear_regression_Form)
        self.label_7.setGeometry(QtCore.QRect(50, 700, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(Linear_regression_Form)
        self.lineEdit_8.setGeometry(QtCore.QRect(140, 700, 113, 21))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_8 = QtWidgets.QLabel(Linear_regression_Form)
        self.label_8.setGeometry(QtCore.QRect(290, 700, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(Linear_regression_Form)
        self.lineEdit_9.setGeometry(QtCore.QRect(360, 700, 113, 21))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_9 = QtWidgets.QLabel(Linear_regression_Form)
        self.label_9.setGeometry(QtCore.QRect(50, 750, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(Linear_regression_Form)
        self.lineEdit_10.setGeometry(QtCore.QRect(140, 750, 113, 21))
        self.lineEdit_10.setObjectName("lineEdit_10")

        self.retranslateUi(Linear_regression_Form)
        QtCore.QMetaObject.connectSlotsByName(Linear_regression_Form)

    def retranslateUi(self, Linear_regression_Form):
        _translate = QtCore.QCoreApplication.translate
        Linear_regression_Form.setWindowTitle(_translate("Linear_regression_Form", "线性回归"))
        self.pushButton.setText(_translate("Linear_regression_Form", "参数估计"))
        self.pushButton_2.setText(_translate("Linear_regression_Form", "线性回归图像"))
        self.label_3.setText(_translate("Linear_regression_Form", "指定点"))
        self.pushButton_3.setText(_translate("Linear_regression_Form", "预测"))
        self.label.setText(_translate("Linear_regression_Form", "a"))
        self.label_2.setText(_translate("Linear_regression_Form", "b"))
        self.label_4.setText(_translate("Linear_regression_Form", "x(用空格间隔样本点)"))
        self.label_5.setText(_translate("Linear_regression_Form", "y(用空格间隔样本点)"))
        self.pushButton_4.setText(_translate("Linear_regression_Form", "假设检验"))
        self.label_6.setText(_translate("Linear_regression_Form", "显著性水平"))
        self.label_7.setText(_translate("Linear_regression_Form", "F值"))
        self.label_8.setText(_translate("Linear_regression_Form", "临界值"))
        self.label_9.setText(_translate("Linear_regression_Form", "检验结果"))
from Plot import Plot


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Linear_regression_Form = QtWidgets.QWidget()
    ui = Ui_Linear_regression_Form()
    ui.setupUi(Linear_regression_Form)
    Linear_regression_Form.show()
    sys.exit(app.exec_())
