# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\94890\Desktop\Mathematical_Statistics\Myfiles\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_6 = QtWidgets.QMenu(self.menu)
        self.menu_6.setObjectName("menu_6")
        self.menu_7 = QtWidgets.QMenu(self.menu)
        self.menu_7.setObjectName("menu_7")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_12 = QtWidgets.QMenu(self.menu_2)
        self.menu_12.setObjectName("menu_12")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_9 = QtWidgets.QMenu(self.menu_3)
        self.menu_9.setObjectName("menu_9")
        self.menu_10 = QtWidgets.QMenu(self.menu_3)
        self.menu_10.setObjectName("menu_10")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menubar)
        self.menu_5.setObjectName("menu_5")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Sd_chi = QtWidgets.QAction(MainWindow)
        self.action_Sd_chi.setObjectName("action_Sd_chi")
        self.action_Sd_t = QtWidgets.QAction(MainWindow)
        self.action_Sd_t.setObjectName("action_Sd_t")
        self.action_Sd_F = QtWidgets.QAction(MainWindow)
        self.action_Sd_F.setObjectName("action_Sd_F")
        self.action_Sd_SingleNormal = QtWidgets.QAction(MainWindow)
        self.action_Sd_SingleNormal.setObjectName("action_Sd_SingleNormal")
        self.action_Sd_DoubleNormal = QtWidgets.QAction(MainWindow)
        self.action_Sd_DoubleNormal.setObjectName("action_Sd_DoubleNormal")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.action_7 = QtWidgets.QAction(MainWindow)
        self.action_7.setObjectName("action_7")
        self.action_11 = QtWidgets.QAction(MainWindow)
        self.action_11.setObjectName("action_11")
        self.action_12 = QtWidgets.QAction(MainWindow)
        self.action_12.setObjectName("action_12")
        self.action_13 = QtWidgets.QAction(MainWindow)
        self.action_13.setObjectName("action_13")
        self.action_a = QtWidgets.QAction(MainWindow)
        self.action_a.setObjectName("action_a")
        self.action_16 = QtWidgets.QAction(MainWindow)
        self.action_16.setObjectName("action_16")
        self.action_18 = QtWidgets.QAction(MainWindow)
        self.action_18.setObjectName("action_18")
        self.action_dulixingjianyan = QtWidgets.QAction(MainWindow)
        self.action_dulixingjianyan.setObjectName("action_dulixingjianyan")
        self.action_Linear_regression = QtWidgets.QAction(MainWindow)
        self.action_Linear_regression.setObjectName("action_Linear_regression")
        self.action_22 = QtWidgets.QAction(MainWindow)
        self.action_22.setObjectName("action_22")
        self.action_23 = QtWidgets.QAction(MainWindow)
        self.action_23.setObjectName("action_23")
        self.action_24 = QtWidgets.QAction(MainWindow)
        self.action_24.setObjectName("action_24")
        self.action_25 = QtWidgets.QAction(MainWindow)
        self.action_25.setObjectName("action_25")
        self.actions = QtWidgets.QAction(MainWindow)
        self.actions.setObjectName("actions")
        self.action_26 = QtWidgets.QAction(MainWindow)
        self.action_26.setObjectName("action_26")
        self.Simple_m_confidence_interval_action = QtWidgets.QAction(MainWindow)
        self.Simple_m_confidence_interval_action.setObjectName("Simple_m_confidence_interval_action")
        self.action_double_confidence_interval = QtWidgets.QAction(MainWindow)
        self.action_double_confidence_interval.setObjectName("action_double_confidence_interval")
        self.action0_1 = QtWidgets.QAction(MainWindow)
        self.action0_1.setObjectName("action0_1")
        self.action_Nonlinear_regression = QtWidgets.QAction(MainWindow)
        self.action_Nonlinear_regression.setObjectName("action_Nonlinear_regression")
        self.menu_6.addAction(self.action_Sd_chi)
        self.menu_6.addAction(self.action_Sd_t)
        self.menu_6.addAction(self.action_Sd_F)
        self.menu_7.addAction(self.action_Sd_SingleNormal)
        self.menu_7.addAction(self.action_Sd_DoubleNormal)
        self.menu.addAction(self.menu_6.menuAction())
        self.menu.addAction(self.menu_7.menuAction())
        self.menu_12.addAction(self.Simple_m_confidence_interval_action)
        self.menu_12.addAction(self.action_double_confidence_interval)
        self.menu_2.addAction(self.menu_12.menuAction())
        self.menu_9.addAction(self.action_a)
        self.menu_9.addAction(self.action_16)
        self.menu_10.addAction(self.action_18)
        self.menu_10.addAction(self.action_dulixingjianyan)
        self.menu_3.addAction(self.menu_9.menuAction())
        self.menu_3.addAction(self.menu_10.menuAction())
        self.menu_4.addAction(self.action_Linear_regression)
        self.menu_4.addAction(self.action_Nonlinear_regression)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "主菜单"))
        self.menu.setTitle(_translate("MainWindow", "抽样分布"))
        self.menu_6.setTitle(_translate("MainWindow", "三大抽样分布"))
        self.menu_7.setTitle(_translate("MainWindow", "正态总体下统计量"))
        self.menu_2.setTitle(_translate("MainWindow", "参数估计"))
        self.menu_12.setTitle(_translate("MainWindow", "参数的区间估计"))
        self.menu_3.setTitle(_translate("MainWindow", "假设检验"))
        self.menu_9.setTitle(_translate("MainWindow", "参数检验"))
        self.menu_10.setTitle(_translate("MainWindow", "非参数检验"))
        self.menu_4.setTitle(_translate("MainWindow", "回归分析"))
        self.menu_5.setTitle(_translate("MainWindow", "帮助"))
        self.action_Sd_chi.setText(_translate("MainWindow", "卡方分布"))
        self.action_Sd_t.setText(_translate("MainWindow", "t分布"))
        self.action_Sd_F.setText(_translate("MainWindow", "F-分布"))
        self.action_Sd_SingleNormal.setText(_translate("MainWindow", "单个正态总体统计量的分布"))
        self.action_Sd_DoubleNormal.setText(_translate("MainWindow", "两个正态总体统计量的分布"))
        self.action_6.setText(_translate("MainWindow", "矩法"))
        self.action_7.setText(_translate("MainWindow", "最大似然法"))
        self.action_11.setText(_translate("MainWindow", "无序性"))
        self.action_12.setText(_translate("MainWindow", "有效性"))
        self.action_13.setText(_translate("MainWindow", "一致性"))
        self.action_a.setText(_translate("MainWindow", "单个正态总体的检验"))
        self.action_16.setText(_translate("MainWindow", "两个正态总体的检验"))
        self.action_18.setText(_translate("MainWindow", "分布函数拟合检验"))
        self.action_dulixingjianyan.setText(_translate("MainWindow", "独立性检验"))
        self.action_Linear_regression.setText(_translate("MainWindow", "直线回归"))
        self.action_22.setText(_translate("MainWindow", "双曲线"))
        self.action_23.setText(_translate("MainWindow", "幂函数"))
        self.action_24.setText(_translate("MainWindow", "指数"))
        self.action_25.setText(_translate("MainWindow", "对数"))
        self.actions.setText(_translate("MainWindow", "s形曲线"))
        self.action_26.setText(_translate("MainWindow", "抛物线"))
        self.Simple_m_confidence_interval_action.setText(_translate("MainWindow", "单个正态分布总体"))
        self.action_double_confidence_interval.setText(_translate("MainWindow", "两个正态分布总体"))
        self.action0_1.setText(_translate("MainWindow", "0-1"))
        self.action_Nonlinear_regression.setText(_translate("MainWindow", "曲线回归"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

