# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\94890\Desktop\Mathematical_Statistics\Myfiles\files\Sd_DoubleNormal.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Sd_DoubleNormal_Form(object):
    def setupUi(self, Sd_DoubleNormal_Form):
        Sd_DoubleNormal_Form.setObjectName("Sd_DoubleNormal_Form")
        Sd_DoubleNormal_Form.resize(1123, 615)
        font = QtGui.QFont()
        font.setPointSize(12)
        Sd_DoubleNormal_Form.setFont(font)
        self.widget = Plot(Sd_DoubleNormal_Form)
        self.widget.setGeometry(QtCore.QRect(110, 190, 901, 391))
        self.widget.setObjectName("widget")
        self.layoutWidget = QtWidgets.QWidget(Sd_DoubleNormal_Form)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 41, 1045, 101))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 6, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 3, 1, 1)
        self.doubleSpinBox_mu2 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_mu2.setMinimum(-1e+31)
        self.doubleSpinBox_mu2.setMaximum(1e+28)
        self.doubleSpinBox_mu2.setObjectName("doubleSpinBox_mu2")
        self.gridLayout.addWidget(self.doubleSpinBox_mu2, 1, 1, 1, 2)
        self.doubleSpinBox_mu1 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_mu1.setMinimum(-1e+31)
        self.doubleSpinBox_mu1.setMaximum(1e+28)
        self.doubleSpinBox_mu1.setObjectName("doubleSpinBox_mu1")
        self.gridLayout.addWidget(self.doubleSpinBox_mu1, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.doubleSpinBox_sigma2 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_sigma2.setMinimum(0.0)
        self.doubleSpinBox_sigma2.setMaximum(1e+28)
        self.doubleSpinBox_sigma2.setProperty("value", 1.0)
        self.doubleSpinBox_sigma2.setObjectName("doubleSpinBox_sigma2")
        self.gridLayout.addWidget(self.doubleSpinBox_sigma2, 1, 4, 1, 1)
        self.doubleSpinBox_sigma1 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_sigma1.setMinimum(0.0)
        self.doubleSpinBox_sigma1.setMaximum(1e+28)
        self.doubleSpinBox_sigma1.setProperty("value", 1.0)
        self.doubleSpinBox_sigma1.setObjectName("doubleSpinBox_sigma1")
        self.gridLayout.addWidget(self.doubleSpinBox_sigma1, 0, 4, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 1, 1, 6)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.spinBox_m1 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_m1.setMinimum(1)
        self.spinBox_m1.setMaximum(999999999)
        self.spinBox_m1.setObjectName("spinBox_m1")
        self.gridLayout_2.addWidget(self.spinBox_m1, 0, 5, 1, 1)
        self.spinBox_m2 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_m2.setMinimum(1)
        self.spinBox_m2.setMaximum(999999999)
        self.spinBox_m2.setObjectName("spinBox_m2")
        self.gridLayout_2.addWidget(self.spinBox_m2, 0, 7, 1, 1)
        self.spinBox_n2 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_n2.setMinimum(2)
        self.spinBox_n2.setMaximum(999999999)
        self.spinBox_n2.setObjectName("spinBox_n2")
        self.gridLayout_2.addWidget(self.spinBox_n2, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 4, 1, 1)
        self.spinBox_n1 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_n1.setMinimum(2)
        self.spinBox_n1.setMaximum(999999999)
        self.spinBox_n1.setObjectName("spinBox_n1")
        self.gridLayout_2.addWidget(self.spinBox_n1, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(Sd_DoubleNormal_Form)
        self.pushButton_4.setGeometry(QtCore.QRect(850, 150, 239, 29))
        self.pushButton_4.setObjectName("pushButton_4")
        self.comboBox = QtWidgets.QComboBox(Sd_DoubleNormal_Form)
        self.comboBox.setGeometry(QtCore.QRect(40, 150, 411, 26))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.widget1 = QtWidgets.QWidget(Sd_DoubleNormal_Form)
        self.widget1.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.widget1.setObjectName("widget1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget2 = QtWidgets.QWidget(Sd_DoubleNormal_Form)
        self.widget2.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.widget2.setObjectName("widget2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget3 = QtWidgets.QWidget(Sd_DoubleNormal_Form)
        self.widget3.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.widget3.setObjectName("widget3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.retranslateUi(Sd_DoubleNormal_Form)
        QtCore.QMetaObject.connectSlotsByName(Sd_DoubleNormal_Form)

    def retranslateUi(self, Sd_DoubleNormal_Form):
        _translate = QtCore.QCoreApplication.translate
        Sd_DoubleNormal_Form.setWindowTitle(_translate("Sd_DoubleNormal_Form", "两个正态总体抽样分布"))
        self.label_6.setText(_translate("Sd_DoubleNormal_Form", "抽样次数m2"))
        self.label_8.setText(_translate("Sd_DoubleNormal_Form", "σ1"))
        self.label_4.setText(_translate("Sd_DoubleNormal_Form", "σ2"))
        self.label_7.setText(_translate("Sd_DoubleNormal_Form", "μ1"))
        self.label_3.setText(_translate("Sd_DoubleNormal_Form", "μ2"))
        self.label.setText(_translate("Sd_DoubleNormal_Form", "样本容量n1"))
        self.label_2.setText(_translate("Sd_DoubleNormal_Form", "抽样次数m1"))
        self.label_5.setText(_translate("Sd_DoubleNormal_Form", "样本容量n2"))
        self.pushButton_4.setText(_translate("Sd_DoubleNormal_Form", "显示图像"))
        self.comboBox.setItemText(0, _translate("Sd_DoubleNormal_Form", "已知方差的两总体样本均值的分布"))
        self.comboBox.setItemText(1, _translate("Sd_DoubleNormal_Form", "已知方差的两总体样本方差比的分布"))
        self.comboBox.setItemText(2, _translate("Sd_DoubleNormal_Form", "方差相等的两总体样本方差比的分布"))

from Plot import Plot

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Sd_DoubleNormal_Form = QtWidgets.QWidget()
    ui = Ui_Sd_DoubleNormal_Form()
    ui.setupUi(Sd_DoubleNormal_Form)
    Sd_DoubleNormal_Form.show()
    sys.exit(app.exec_())

