# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\94890\Desktop\YTfiles\Myfiles\Myfiles\files\Sd_f.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Sd_f_Form(object):
    def setupUi(self, Sd_f_Form):
        Sd_f_Form.setObjectName("Sd_f_Form")
        Sd_f_Form.resize(903, 511)
        font = QtGui.QFont()
        font.setPointSize(12)
        Sd_f_Form.setFont(font)
        self.label_4 = QtWidgets.QLabel(Sd_f_Form)
        self.label_4.setGeometry(QtCore.QRect(370, 10, 241, 31))
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setObjectName("label_4")
        self.widget = Plot(Sd_f_Form)
        self.widget.setGeometry(QtCore.QRect(360, 50, 511, 431))
        self.widget.setObjectName("widget")
        self.widget1 = QtWidgets.QWidget(Sd_f_Form)
        self.widget1.setGeometry(QtCore.QRect(10, 170, 343, 178))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton_one = QtWidgets.QRadioButton(self.widget1)
        self.radioButton_one.setChecked(True)
        self.radioButton_one.setObjectName("radioButton_one")
        self.horizontalLayout_3.addWidget(self.radioButton_one)
        self.radioButton_few = QtWidgets.QRadioButton(self.widget1)
        self.radioButton_few.setObjectName("radioButton_few")
        self.horizontalLayout_3.addWidget(self.radioButton_few)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.doubleSpinBox_f_n = QtWidgets.QDoubleSpinBox(self.widget1)
        self.doubleSpinBox_f_n.setDecimals(0)
        self.doubleSpinBox_f_n.setObjectName("doubleSpinBox_f_n")
        self.gridLayout.addWidget(self.doubleSpinBox_f_n, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget1)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.doubleSpinBox_f_m = QtWidgets.QDoubleSpinBox(self.widget1)
        self.doubleSpinBox_f_m.setDecimals(0)
        self.doubleSpinBox_f_m.setObjectName("doubleSpinBox_f_m")
        self.gridLayout.addWidget(self.doubleSpinBox_f_m, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.widget1)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget1)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.doubleSpinBox_f_arfa = QtWidgets.QDoubleSpinBox(self.widget1)
        self.doubleSpinBox_f_arfa.setMinimum(0.01)
        self.doubleSpinBox_f_arfa.setMaximum(0.99)
        self.doubleSpinBox_f_arfa.setSingleStep(0.01)
        self.doubleSpinBox_f_arfa.setObjectName("doubleSpinBox_f_arfa")
        self.horizontalLayout.addWidget(self.doubleSpinBox_f_arfa)
        self.pushButton_f_quantile_plot = QtWidgets.QPushButton(self.widget1)
        self.pushButton_f_quantile_plot.setObjectName("pushButton_f_quantile_plot")
        self.horizontalLayout.addWidget(self.pushButton_f_quantile_plot)
        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_f_quantile = QtWidgets.QPushButton(self.widget1)
        self.pushButton_f_quantile.setObjectName("pushButton_f_quantile")
        self.horizontalLayout_2.addWidget(self.pushButton_f_quantile)
        self.lineEdit_f_quantile = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_f_quantile.setReadOnly(True)
        self.lineEdit_f_quantile.setObjectName("lineEdit_f_quantile")
        self.horizontalLayout_2.addWidget(self.lineEdit_f_quantile)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)

        self.retranslateUi(Sd_f_Form)
        QtCore.QMetaObject.connectSlotsByName(Sd_f_Form)

    def retranslateUi(self, Sd_f_Form):
        _translate = QtCore.QCoreApplication.translate
        Sd_f_Form.setWindowTitle(_translate("Sd_f_Form", "f分布"))
        self.label_4.setText(_translate("Sd_f_Form", "f分布图像："))
        self.radioButton_one.setText(_translate("Sd_f_Form", "单个图像"))
        self.radioButton_few.setText(_translate("Sd_f_Form", "多个图像"))
        self.label.setText(_translate("Sd_f_Form", "输入n2值："))
        self.label_2.setText(_translate("Sd_f_Form", "输入n1值："))
        self.pushButton.setText(_translate("Sd_f_Form", "显示f分布图像"))
        self.label_3.setText(_translate("Sd_f_Form", "输入α值"))
        self.pushButton_f_quantile_plot.setText(_translate("Sd_f_Form", "显示分位点图像"))
        self.pushButton_f_quantile.setText(_translate("Sd_f_Form", "显示分位点"))
from Plot import Plot


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Sd_f_Form = QtWidgets.QWidget()
    ui = Ui_Sd_f_Form()
    ui.setupUi(Sd_f_Form)
    Sd_f_Form.show()
    sys.exit(app.exec_())
